### ISSUE TITLE
Update tokio to 1.0

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/audioipc-2#110]
Seems like this holds Gecko from updating to tokio 1.0 - https://searchfox.org/mozilla-central/search?q=tokio+%3D&path=&case=true&regexp=false

**Comment by nils-ohlmeier** [comment]
There are better experts then me who should comment on this, but it is my understanding that tokio 1.0 doesn't work for audioipc as it dropped some feature we depend on.
If I'm not mistaken the current plan for audioipc is to remove tokio from it's dependencies, as thus then no longer block other projects in Gecko from upgrading.

**Comment by kinetiknz** [comment]
Nils is correct - I commented here: https://github.com/mozilla/audioipc-2/pull/117#issuecomment-797268606

Removing the tokio dependency will be tracked in [bug 1697845](https://bugzilla.mozilla.org/show_bug.cgi?id=1697845).
