### ISSUE TITLE
upgrade iovec requirement to 0.2

### ISSUE THREAD

**Issue by froydnj** [mozilla/audioipc-2#48]
The reasoning here is similar to #47; `iovec 0.1` depends on an older version of `winapi`, whereas `iovec 0.2` depends on a newer version.

**Comment by froydnj** [comment]
Argh, apparently carllerche/iovec#16 means that 0.2 might not get released for a while...

**Comment by kinetiknz** [comment]
Looks like this is still blocked upstream.

**Comment by kinetiknz** [comment]
I believe this is no longer an issue - 7ca93a229ecd20da94d53d9629174aaad074f9b4 made our `iovec` dependency `unix` only, avoiding the `winapi 0.2` issue.  Also, `iovec 0.1.4` dropped the `winapi 0.2` dependency.
