### ISSUE TITLE
Safer shared memory API

### ISSUE THREAD

**Issue by kinetiknz** [mozilla/audioipc-2#67]
Following on from the discussion in https://github.com/djg/audioipc-2/pull/63, shm.rs and the exposed API used by callers can probably be improved to be safer.  Right now, synchronization of the shared memory is completely external, making shm.rs unsafe despite being marked as safe.

**Comment by kinetiknz** [comment]
Also worth trying to make the shm anonymous rather than relying on a temporary file.

We can do this on Windows by making the shm "pagefile backed" by passing INVALID_HANDLE_VALUE to CreateFileMapping.

For Linux, we'd probably need memfd which isn't available on older kernels.

macOS I need to research further.

**Comment by ChunMinChang** [comment]
> We can do this on Windows by making the shm "pagefile backed" by passing INVALID_HANDLE_VALUE to CreateFileMapping.

For Windows, it's has done in #115, right?

**Comment by kinetiknz** [comment]
That's right.  We're also using memfd since https://github.com/mozilla/audioipc-2/pull/93.  I'll take a look at improving the situation for macOS next.

**Comment by kinetiknz** [comment]
> I'll take a look at improving the situation for macOS next.

Looks like the best available option is `shm_open`, which isn't anonymous, but it's likely better than creating our own temp files.  PR https://github.com/mozilla/audioipc-2/pull/119 adds this.

**Comment by kinetiknz** [comment]
This is now complete.
